CoHouseTeam/cohouse-client

- src/features/tasks/components/DaySelectModal.tsx
주간 업무표의 요일 선택 모달에 확인/취소 버튼 추가
- 확인 취소 버튼 추가
> feat: 요일 선택 모달 확인/취소 버튼 추가

- src/libs/utils/format.ts
날짜를 일관된 형식으로 표시하기 위한 유틸리티 함수를 추가
`formatDateWithWeekday`: YYYY.MM.DD(요일) 포맷으로 변환
해당 사항 없음 (UI 변경 없음)
- npm run dev 실행
- 콘솔 혹은 샘플 코드에서 아래 유틸 호출
```
formatDateWithWeekday(new Date("2025-08-22")) // 2025.08.22(금)
```
- 예상 출력과 일치하는지 확인
> feat(utils): add formatDateWithWeekday

- src/mocks/db/tasks.ts
- src/mocks/handlers/tasksHandlers.ts
- src/types/tasks.ts
Reverts CoHouseTeam/cohouse-client#28
데이터베이스 추가
Handler에 할일 배정, 담당자 변경 요청, 히스토리 관련 handler 추가 구현
> Revert "feat: TasksHandler 구현"

- src/mocks/db/tasks.ts
- src/mocks/handlers/tasksHandlers.ts
- src/types/tasks.ts
TasksHandler 추가 구현
- 데이터베이스 추가
- Handler에 할일 배정, 담당자 변경 요청, 히스토리 관련 handler 추가 구현
> feat: TasksHandler 추가 구현

- src/features/mainpage/components/CalendarBox.tsx
- src/pages/MainPage.tsx
- src/types/main.ts
캘린더 날짜 클릭 시 상세 일정에 날짜 변동 안되는 오류
- 날짜 변동되게 수정
> feat: 캘린더 오류 수정

- src/features/settlements/components/SettlementCreateModal.tsx
- 정산 등록 모달에 **영수증 이미지 선택/미리보기/선택 취소 UI** 추가
- 현재는 프론트 로컬 동작까지만 구현했고 **실제 업로드(API 연동)는 후속 PR**에서 처리
- 정산 등록 모달(SettlementCreateModal)
- 총 정산 금액 입력 왼쪽 작은 박스를 **영수증 업로드 트리거 + 미리보기 영역**으로 변경
- 이미지 파일 선택 시 즉시 **미리보기 썸네일** 표시
- 썸네일 우상단 **✕ 버튼으로 선택 취소** 가능 (미리보기 URL 정리까지 포함)
- **이미지 아닌 파일** 선택 시 간단한 에러 메시지 표시
- 내부 상태
- `receiptFile`, `receiptPreview`, `receiptError` 추가 (API 연동 시 활용 예정)
- `URL.createObjectURL` / `URL.revokeObjectURL`로 미리보기 관리 및 메모리 누수 방지
> Note: **서버 업로드(POST/PUT/DELETE) 및 OCR 금액 자동반영은 미포함** — 후속 PR에서 추가
- 금액 입력 칸 왼쪽 작은 박스 클릭 → 파일 선택 → 썸네일 노출 → ✕로 취소
1. 정산 등록 모달을 연다.
2. **총 정산 금액** 입력 왼쪽의 작은 박스를 클릭해 이미지 파일을 선택한다.
- 선택 즉시 박스에 **미리보기 썸네일**이 표시되어야 한다.
3. **✕ 버튼**을 누르면 썸네일이 사라지고, 다시 파일을 선택할 수 있어야 한다.
4. `readOnly`(상세 모드)로 열었을 때는 업로드/취소가 **비활성화**되어야 한다.
5. 같은 파일을 연속으로 선택해도 onChange가 …
> feat(settlement-create): 영수증 이미지 업로드 기능 추가

- src/features/tasks/components/HistoryModal.tsx
- src/pages/Tasks.tsx
업무 내역 모달에 필터링 추가
- 필터링 추가
- 할일 페이지에서 랜덤 배정 클릭 후 요청하기 버튼 표시
> feat: 업무 내역 필터링 추가

- src/app/store.ts
- src/features/mainpage/components/GroupCreateModal.tsx
- src/features/mainpage/components/GroupInviteModal.tsx
- src/libs/api/groups.ts
- src/libs/utils/auth.ts
- src/pages/Login.tsx
- src/pages/MainPage.tsx
- src/types/main.ts
그룹 생성과 그룹 상태 확인 API 연동
- 그룹 생성 API 연동
- 그룹 상태 확인 API 연동
- zustand로 그룹 상태 관리
- 그룹 초대 모달 추가
> feat: 그룹 상태 API 연동

- src/features/mainpage/components/GroupCreateModal.tsx
- src/libs/api/groups.ts
- src/pages/MainPage.tsx
로그아웃 상태에서, 그룹 상태 오류 문구 뜨는 오류 수정
- 로그인 상태에서만 그룹 상태 오류 확인 가능
)
> fix: 로그아웃 상태에서 그룹 오류 문구

- .env.development
- src/libs/api/axios.ts
> .env.development 수정

- src/app/routes.tsx
- src/features/mainpage/components/NicknameModal.tsx
- src/libs/api/groups.ts
- src/pages/GroupInvite.tsx
- src/types/main.ts
그룹 승인, 닉네임 등록을 위한 페이지 추가
- 그룹 초대 승인 페이지 추가 (계획은 모달이었으나 페이지로 변경)
- 승인 시 닉네임 등록
**- api 등록하였으나 추후 확인 필요**
> feat: 그룹 초대 승인 페이지 추가

- src/pages/MainPage.tsx
- src/pages/Tasks.tsx
토큰 확인과 group 상태 확인 api 중복 호출 문제 수정
> fix: 중복 호출 문제 수정

- src/features/tasks/components/DaySelectModal.tsx
- src/features/tasks/components/TaskTable.tsx
- src/libs/api/tasks.ts
- src/pages/Tasks.tsx
주간 업무표 templete 삭제 표시 추가
- 삭제 api 연동
> feat: 주간 업무표 templete 삭제 표시 추가

- src/pages/GroupInvite.tsx
> feat: 초대 페이지 api 연동

- src/app/store.ts
- src/components/NavBar.tsx
- src/libs/api/endpoints.ts
- src/libs/api/profile.ts
- src/pages/MainPage.tsx
메인페이지에서 사용하는 API 일부 연동
- 메인페이지에 사용자 이름 연동하여 표시
- 메뉴창 열었을때 요일선택 화살표가 뚫고나오는 오류 수정
> feat: 메인페이지 API 연동

- src/features/tasks/components/ExchangeModal.tsx
- src/libs/api/tasks.ts
- src/pages/MainPage.tsx
- src/pages/Tasks.tsx
- src/types/tasks.ts
업무 교환 요청 API 연동, 업무 교환 요청 모달 체크박스로 수정
- 연동 후 기능 추가
- 업무 교환 요청 모달 라디오 -> 체크박스 수정
- 전체 선택 가능
- 메인페이지 그룹 박스 오류 수정
- 할일 페이지 토큰 관련 추후 수정
> feat: 업무 교환 요청 기능 추가

- src/app/tasksStore.ts
- src/features/mainpage/components/CalendarBox.tsx
- src/features/mainpage/components/CalendarDateDots.tsx
- src/features/mainpage/components/GroupInviteInputModal.tsx
- src/features/mainpage/components/TodoListBox.tsx
- src/features/mainpage/components/UncompletedTasksModal.tsx
- src/libs/api/endpoints.ts
- src/libs/api/settlements.ts
- src/pages/MainPage.tsx
- src/types/main.ts
- src/types/tasks.ts
리팩토링
- 메인페이지 컴포넌트 리팩토링
- taskStore 정리
- 정산 api 임시 추가
> Refactor: 메인페이지 컴포넌트 리팩토링

- src/features/tasks/components/TaskTable.tsx
- src/libs/hooks/taskpage/useExchangeRequest.ts
- src/libs/hooks/taskpage/useRandomAssign.ts
- src/pages/Tasks.tsx
> Refactor: 할일페이지 리팩토링

- src/features/mainpage/components/GroupCreateModal.tsx
그룹 생성 시 닉네임 자동입력
- 닉네임 입력 창 삭제
- 닉네임에 이름 자동 입력
> fix: 그룹 생성 시 닉네임 자동 입력

- src/features/mainpage/components/CalendarBox.tsx
- src/features/mainpage/components/CalendarDateDots.tsx
컬러점이 추가되면 날짜가 밀리는 오류 수정
- 컬러점 추가 로직 수정
> fix: 캘린더의 컬러점 위치 수정
